services:
  service-client:
    container_name: service-client
    build: ./service-client
    tty: true
    volumes:
      - ./service-client:/service-client
      - ./service-client/node_modules:/service-client/node_modules:delegated
      - next_cache_volume:/service-client/.next
      - build_volume:/service-client/build:nocopy
      - ./certs:/service-client/certs
    ports:
      - "3000:3000"

volumes:
  next_cache_volume:
  build_volume:
