import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<head>
				<Script
					strategy="beforeInteractive"
					src="//cdn.8thwall.com/web/aframe/8frame-1.4.1.min.js"
				/>
				{/* XR Extras - provides utilities like load screen, almost there, and error handling.
					See github.com/8thwall/web/tree/master/xrextras */}
				<Script
					strategy="beforeInteractive"
					src="//cdn.8thwall.com/web/xrextras/xrextras.js"
				/>

				{/* Landing Pages - see https://www.8thwall.com/docs/web/#landing-pages */}
				<Script
					strategy="beforeInteractive"
					src={"//cdn.8thwall.com/web/landing-page/landing-page.js"}
				/>
				{/* 8thWall Web - Replace the app key here with your own app key */}
				<Script
					async
					src={`//apps.8thwall.com/xrweb?appKey=${process.env.NEXT_PUBLIC_8TH_WALL_APP_KEY}`}
				/>
			</head>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
