import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script async src={`//apps.8thwall.com/xrweb?appKey=${process.env.NEXT_PUBLIC_8TH_WALL_APP_KEY}`} />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
