import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<Head>
				<meta name="8thwall:renderer" content="aframe:1.1.0" />
				<meta name="8thwall:package" content="@8thwall.xrextras" />
				<meta name="8thwall:package" content="@8thwall.landing-page" />
				<meta name="8thwall:package" content="@react.react" />
				<meta name="8thwall:package" content="@react.react-dom" />
				<meta name="8thwall:package" content="@react.react-router-dom" />
			</Head>
			<Script
				async
				src={`//apps.8thwall.com/xrweb?appKey=${process.env.NEXT_PUBLIC_8TH_WALL_APP_KEY}`}
			/>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
